config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  devise_for :users
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  has_one_attached :media
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:title, :body, :url, :media, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_svg(name, options={})
        options[:title] ||= name.underscore.humanize
        options[:aria] = true
        options[:nocomment] = true
        options[:class] = options.fetch(:styles, "fill-current text-gray-500")
        filename = "#{name}.svg"
        inline_svg_tag(filename, options)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webbit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-200 relative h-screen overflow-x-hidden">
    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
            <%= message %>
          </div>
        </div>
      <% end %>

      <% if type == "notice" %>
        <div class="bg-green-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
            <%= message %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :media, style: "display: block" %>
    <%= form.file_field :media %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/_submission.html.erb
<div id="<%= dom_id submission %>">
  <p>
    <strong>Title:</strong>
    <%= submission.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= submission.body %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= submission.url %>
  </p>

  <p>
    <strong>Media:</strong>
    <%= link_to submission.media.filename, submission.media if submission.media.attached? %>
  </p>

  <p>
    <strong>User:</strong>
    <%= submission.user_id %>
  </p>

</div>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Show this submission", @submission %> |
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Submissions</h1>

<div id="submissions">
  <% @submissions.each do |submission| %>
    <%= render submission %>
    <p>
      <%= link_to "Show this submission", submission %>
    </p>
  <% end %>
</div>

<%= link_to "New submission", new_submission_path %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @submission %>

<div>
  <%= link_to "Edit this submission", edit_submission_path(@submission) %> |
  <%= link_to "Back to submissions", submissions_path %>

  <%= button_to "Destroy this submission", @submission, method: :delete %>
</div>